Bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include

from announcement.views import postlist

urlpatterns = [
    path('', postlist, name='post_list'),

    path('admin/', admin.site.urls, name='admin'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include("accounts.urls")),
    path('post/', include('announcement.urls')),
    path('subscription/', include('subscription.urls')),

    path('tinymce/', include('tinymce.urls')),

]

accounts/urls.py
from django.urls import path
from .views import SignUp, ConfirmEmailCodeView, profile_posts, profile_comments

urlpatterns = [
    path('', profile_posts, name='account_profile'),
    path('comments', profile_comments, name='account_profile_comments'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('confirm-email/', ConfirmEmailCodeView.as_view(), name='confirm_email'),
]

subscription/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class SubscriptionMessages(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    data_published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_list')

templates/confirm_email.html
{% extends 'default.html' %}
{% load static %}

{% block title %}
    Подтвержение почты
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card rounded-5 bluefon">
        <div class="card-body">
            <h5 class="card-title text-center">Подтверждение почты:</h5>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="greenfon w-100 inputbutton" type="submit" value="Отправить" />
            </form>
        </div>
    </div>
{% endblock content %}

templates/default.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
    <title>{% block title %} {% endblock title %}</title>
    {% block head %} {% endblock head %}
</head>
<body style="background-image: url({% static 'fon.jpg' %})">
    <div>
        <nav class="p-4">
            <div class="container d-flex justify-content-between align-items-center">
                <a href="/" class="bluetext fs-1">Доска объявлений</a>
                <div class="d-flex gap-3">
                    {% if perms.subscription.add_subscriptionmessages %}
                        <a href="{% url 'Subscription_Messages_create' %}" class="bluefon">Создать новость</a>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                        <a href="{% url 'account_profile' %}" class="bluefon">Профиль</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="bluefon">Войти</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column align-items-center">
            {% block content %} {% endblock content %}
        </div>
    </div>
    <script href="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/post.html
{% extends 'default.html' %}
{% load static %}
{% load i18n %}

{% block title %}
   Объявление
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon">
        <div class="card-body">
            <h5 class="card-title fs-3">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 fs-4">{{ post.author.username }} - {{ post.date_posted|date:"d.m.Y" }}</h6>
            <p class="card-text fs-4">{{ post.content|safe }}</p>
            {% if post.author == author %}
                <a href="{% url 'post_update' post.id %}" class="greenfon">Редактировать</a>
                <a href="{% url 'post_delete' post.id %}" class="redfon">Удалить</a>
            {% else %}
                <div class="m-5 card">
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input class="greenfon inputbutton" type="submit" value="Save" />
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/post_del.html
{% extends 'default.html' %}
{% load i18n %}

{% block title %}
    Объявления
{% endblock %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon">
        <div class="card-body">
            <h1 class="card-title">Удалиние объявления</h1>
            <form action="" method="post">
                {% csrf_token %}
                <h4 class="card-text">Удалить объявление "{{ object.title }}"?</h4>
                <input class="redfon inputbutton" type="submit" value="Delete" />
            </form>
        </div>
    </div>
{% endblock content %}

templates/post_edit.html
{% extends 'default.html' %}
{% load static %}

{% block title %}
    Объявления
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon card-body">
        <p class="text-white fs-1 text-center">Объявление</p>
        <form action="" method="post" class="form-floating">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <input class="greenfon inputbutton" type="submit" value="Save" />
        </form>
    </div>
{% endblock content %}

templates/posts.html
{% extends 'default.html' %}
{% load custom_tags %}
{% load static %}
{% load i18n %}

{% block title %}
   Доска объявлений
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon p-2">
        <div class="card-body">
            <h5 class="card-title fs-3 text-center">Фильтр</h5>
            <form action="" method="get" class="form-floating">
                {{ filterset.form.as_p }}
                <input class="orangefon inputbutton" type="submit" value="Найти" />
            </form>
        </div>
    </div>
    {% if posts %}
        {% for post in posts %}
            <div class="m-5 card w-75 rounded-5 bluefon">
                <div class="card-body">
                    <h5 class="card-title fs-3">{{ post.title }}</h5>
                    <h6 class="card-subtitle mb-2 fs-4">{{ post.author.username }} - {{ post.date_posted|date:"d.m.Y" }}</h6>
                    <p class="card-text fs-4">{{ post.content|safe }}</p>
                    {% if post.author == current_user %}
                        <a href="{% url 'post_update' post.id %}" class="greenfon">Редактировать</a>
                        <a href="{% url 'post_delete' post.id %}" class="redfon">Удалить</a>
                    {% else %}
                        <a href="{% url 'post_detail' post.id %}" class="orangefon">Откликнуться</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h2 class="bluefon bluefontext text-center mt-5 fs-2">Объявлений нет</h2>
    {% endif %}
    <div class="m-5 d-flex justify-content-center">
        {% if page_obj.has_previous %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" href="?{% url_replace page=1 %}">Начало</a>
            {% if page_obj.previous_page_number != 0 %}
                <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% else %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" aria-disabled="true">Начало</a>
        {% endif %}

        <a class="bluefon border-end rounded-0" aria-disabled="true">{{ page_obj.number }}</a>

        {% if page_obj.has_next %}
            <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" href="?{% url_replace page=paginator.num_pages %}">Конец</a>
        {% else %}
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" aria-disabled="true">Конец</a>
        {% endif %}
    </div>
{% endblock content %}

templates/profile.html
{% extends 'default.html' %}
{% load custom_tags %}
{% load static %}
{% load i18n %}

{% block title %}
   Профиль
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon">
        <div class="card-body">
            <h5 class="card-title text-center fs-2">Профиль</h5>
            <h5 class="card-title fs-3">{{ current_user.username }}</h5>
            <h6 class="card-subtitle mb-2 fs-4">{{ current_user.email }}</h6>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="redfon inputbutton">Выйти из аккаунта</button>
            </form>
        </div>
    </div>
    <div class="mb-5 card w-75 rounded-5 bluefon">
        <div class="card-body">
            <h5 class="card-title fs-3">Хотите получать новостные рассылки на электронную почту?</h5>
            {% if userprofile.is_subscribed %}
                <form action="{% url 'subscribe' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="action" value="unsubscribe">
                    <button type="submit" class="redfon inputbutton">Отписаться</button>
                </form>
            {% else %}
                <form action="{% url 'subscribe' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    <input type="hidden" name="action" value="subscribe">
                    <button type="submit" class="greenfon inputbutton">Подписаться</button>
                </form>
            {% endif %}
        </div>
    </div>
    <div class="d-flex w-75">
        <a href="" class="w-50 bluebuttonfon rounded-end-0 border-end rounded-start-5">Мои объявления</a>
        <a href="{% url 'account_profile_comments' %}" class="w-50 bluebuttonfon rounded-start-0 border-start rounded-end-5">Ответы на мои объявления</a>
    </div>
    <div class="m-5 card w-75 rounded-5 bluefon p-2">
        <div class="card-body">
            <h5 class="card-title fs-3 text-center">Фильтр</h5>
            <form action="" method="get" class="form-floating">
                {{ filterset.form.as_p }}
                <input class="orangefon inputbutton" type="submit" value="Найти" />
            </form>
        </div>
    </div>
    {% if posts %}
        <h2 class="bluefon bluefontext text-center mt-5 fs-2">Мои объявления</h2>
        <a href="{% url 'post_create' %}" class="greenfon mt-5">Создать новое объявление</a>
        {% for post in posts %}
            {% if not post.status %}
                <div class="m-5 card w-75 rounded-5 bluefon">
                    <div class="card-body">
                        <h5 class="card-title fs-3">{{ post.title }}</h5>
                        <h6 class="card-subtitle mb-2 fs-4">{{ post.author.username }} - {{ post.date_posted|date:"d.m.Y" }}</h6>
                        <p class="card-text fs-4">{{ post.content|safe }}</p>
                        <a href="{% url 'post_update' post.id %}" class="greenfon">Редактировать</a>
                        <a href="{% url 'post_delete' post.id %}" class="redfon">Удалить</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <h2 class="bluefon bluefontext text-center mt-5 fs-2">Объявлений нет</h2>
        <a href="{% url 'post_create' %}" class="greenfon mt-5">Создать новое объявление</a>
    {% endif %}
    <div class="m-5 d-flex justify-content-center">
        {% if page_obj.has_previous %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" href="?{% url_replace page=1 %}">Начало</a>
            {% if page_obj.previous_page_number != 0 %}
                <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% else %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" aria-disabled="true">Начало</a>
        {% endif %}

        <a class="bluefon border-end rounded-0" aria-disabled="true">{{ page_obj.number }}</a>

        {% if page_obj.has_next %}
            <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" href="?{% url_replace page=paginator.num_pages %}">Конец</a>
        {% else %}
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" aria-disabled="true">Конец</a>
        {% endif %}
    </div>
{% endblock content %}

templates/profile_comments.html
{% extends 'default.html' %}
{% load custom_tags %}
{% load static %}
{% load i18n %}

{% block title %}
   Доска объявлений
{% endblock title %}

{% block head %}
    <link href="{% static 'css/posts.css' %}" rel="stylesheet" />
{% endblock head %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon">
        <div class="card-body">
            <h5 class="card-title text-center fs-2">Профиль</h5>
            <h5 class="card-title fs-3">{{ current_user.username }}</h5>
            <h6 class="card-subtitle mb-2 fs-4">{{ current_user.email }}</h6>
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="redfon inputbutton">Выйти из аккаунта</button>
            </form>
        </div>
    </div>
    <div class="d-flex w-75">
        <a href="{% url 'account_profile' %}" class="w-50 bluebuttonfon rounded-end-0 border-end rounded-start-5">Мои объявления</a>
        <a href="" class="w-50 bluebuttonfon rounded-start-0 border-start rounded-end-5">Ответы на мои объявления</a>
    </div>
    <div class="m-5 card w-75 rounded-5 bluefon p-2">
        <div class="card-body">
            <h5 class="card-title fs-3 text-center">Фильтр</h5>
            <form action="" method="get" class="form-floating">
                {{ filterset.form.as_p }}
                <input class="orangefon inputbutton" type="submit" value="Найти" />
            </form>
        </div>
    </div>
    {% if comments %}
        <h2 class="bluefon bluefontext text-center mt-5 fs-2">Ответы</h2>
        {% for comment in comments %}
            {% if comment.status == 'Not defined' %}
                <div class="m-5 card w-75 rounded-5 bluefon">
                    <div class="card-body">
                        <h5 class="card-title fs-3">Ответ на запись "{{ comment.post.title }}"</h5>
                        <h5 class="card-title fs-3">Отправитель: {{ comment.author.username }}</h5>
                        <p class="card-text fs-4">Сообщение: {{ comment.text }}</p>
                        <a href="{% url 'accept_comment' comment.pk %}" class="greenfon">Принять</a>
                        <a href="{% url 'reject_comment' comment.pk %}" class="redfon">Отклонить</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <h2 class="bluefon bluefontext text-center mt-5 fs-2">Ответов нет</h2>
    {% endif %}
    <div class="m-5 d-flex justify-content-center">
        {% if page_obj.has_previous %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" href="?{% url_replace page=1 %}">Начало</a>
            {% if page_obj.previous_page_number != 0 %}
                <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% else %}
            <a class="bluebuttonfon rounded-end-0 border-end rounded-start-5" aria-disabled="true">Начало</a>
        {% endif %}

        <a class="bluefon border-end rounded-0" aria-disabled="true">{{ page_obj.number }}</a>

        {% if page_obj.has_next %}
            <a class="bluebuttonfon border-end rounded-0" href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" href="?{% url_replace page=paginator.num_pages %}">Конец</a>
        {% else %}
            <a class="bluebuttonfon rounded-start-0 rounded-end-5" aria-disabled="true">Конец</a>
        {% endif %}
    </div>
{% endblock content %}

templates/subscription_messages_create.html
{% extends 'default.html' %}
{% load static %}

{% block title %}
    Создание новости
{% endblock title %}

{% block content %}
    <div class="m-5 card w-75 rounded-5 bluefon card-body">
        <p class="text-white fs-1 text-center">Создание новости</p>
        <form action="" method="post" class="form-floating">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media }}
            <p class="text-white fs-1 text-center">Внимание, перед отправкой убедитесь, что вы проверили содержимое новостной рассылки. После отправки отменить будет невозможно.</p>
            <input class="greenfon inputbutton" type="submit" value="Save" />
        </form>
    </div>
{% endblock content %}